services:
  slack-bot:
    build: .
    container_name: mnemo-slack-bot
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      - mnemo-net
    restart: on-failure

networks:
  mnemo-net:
    external: true
    name: mnemo-net
