services:
  slack-bot:
    build: .
    container_name: belleq-slack-bot
    ports:
      - "3000:3000"
    env_file: .env
    networks:
      - belleq-net
    restart: on-failure

networks:
  belleq-net:
    external: true
    name: belleq-net
